# Build the package with graph-cut support and runs the graphcut tests
# This test is kept separate, as the graphcut functionality is optional and unstable
# Triggered whenever a PR into the main or a Release* branch is opened
# Triggered for each new published release

name: Build and test (w graphcut)

on:
  release:
      types: [published]
  pull_request:
    branches: [ "master", "Release*" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install system dependencies for graphcut functionality
      run: sudo apt-get install -y libboost-python-dev build-essential
    - name: Install with test dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -v .[test]
    - name: Check
      run: |
        ls -al
        echo "$PWD"
        cd tests && python -c "import medpy; print(medpy.__file__)"
    - name: Test with pytest (graphcut test only)
      run: cd tests && pytest graphcut_/*
