# Runs the pre-commit hooks to make sure that all pushes are properly and consistently treated
# Also triggers for PRs (potentially coming from external) into master and Release* branches

name: Pre-commit hooks

on:
  push:
    branches: ['**'] # note: without branches would execute for tags, too
  pull_request:
    branches: [ "master", "Release*" ]

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.x
    - uses: pre-commit/action@v3.0.0
    - uses: pre-commit-ci/lite-action@v1.0.1
      if: always()
